### ISSUE TITLE
Anti-mob script

### ISSUE THREAD

**Issue by OpalMoonstride** [SXRWahrheit/Denizen-Scripts#1]
Thanks, so much for linking the updated the script! It looks to work perfectly, other than one thing: my console keeps spamming me with 

"ERROR in Script 'YAML ANTI-SPAWNER SCRIPT'! Tag <yaml[antispawner-flags].read[entities.spawned-by-spawner].contains[<context.entity.uuid>]> is invalid!

I receive zero loot from any spawner mobs, which is overall fine, but I'm taking a wild guess this might be why?

**Comment by SXRWahrheit** [comment]
Hi! Known issue as a result of some recent updates to Denizen and MM. I'm taking the Illinois Bar Exam in two weeks and will be doing some script updates (including this) afterwards.

**Comment by SXRWahrheit** [comment]
Brief update - I'm waiting on the mmDA dev to update the plugin to accommodate the new MythicMobs API. Will close this issue when mmDA and the script are updated!

**Comment by SXRWahrheit** [comment]
Hi, mmDA updated! I updated the farm script and tested it against Denizen-Developmental #420 and [BerndiVader/mmDenizenAddon](https://github.com/BerndiVader/mmDenizenAddon) 0.500a. You can download that verison here: https://github.com/BerndiVader/mmDenizenAddon/blob/764b9dd4c0994971e228a52c71b7e7cb94a178dd/mmDenizenAddon.jar

**Comment by SXRWahrheit** [comment]
I forgot to add the lootdrop event in the samelocation script for the linked commit - if you get the latest version, it should work.
